id: 'declarative-product'
type: core
name: 'product'
title: 'Products'
description: ''
color: '#57D9A3'
icon: 'regular-products'
entity: 'product'

navigation:
    - id: 'declarative-product'
      path: 'declarative.product.list'
      label: 'Products (D)'
      color: '#57D9A3'
      icon: 'regular-products'
      position: 11
      parent: 'sw-catalogue'

routes:
    list:
        name: list
        columns:
            - name
            - productNumber
            - manufacturer.name
            - active
            - sales
            - stock
            - availableStock
            - createdAt
            - updatedAt
    detail:
        name: detail
